# ./frontend/Dockerfile.prod
FROM nginx:alpine
COPY frontend/dist/angular/browser /usr/share/nginx/html

# docker build -f frontend/Dockerfile.prod -t frontopti:latest .
# docker tag frontopti nujabb/front-opti:latest
# docker push nujabb/front-opti:latest