# Utilisez l'image Node.js
FROM node:20.15.1

# Créez le répertoire de l'application
WORKDIR /app

# Copiez package.json et package-lock.json
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Permet un "watch" plus efficace sur Docker (surveille les fichiers)
RUN npm install chokidar --save-dev

# Copiez tout le reste du code de l'application
COPY . .

# Exposez le port
EXPOSE 4200

# Commande pour démarrer l'application
# CMD ["npm", "start"]
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]