# Effectivement, ce n’est pas du tout “con”. 
# C’est même une bonne pratique d’allier les deux : bind mounts pour le code, volumes nommés pour les dépendances. 
# Cela combine l’agilité du développement avec la stabilité du rendu final.

services:

  apache:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
    networks:
      - mynetwork


  php:
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    container_name: php-symfony
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html # bind mounts
      - vendor:/var/www/html/vendor # volume nommé
      - var:/var/www/html/var # volume nommé
    networks:
      - mynetwork
    depends_on:
      - postgres
      - mailer




  postgres:
    image: postgres:15  # mieux que "latest"
    environment:
      POSTGRES_DB: bubblebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persiste les données de session et la configuration


  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"  # Interface web de Mailpit
    networks:
      - mynetwork
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: angular
    working_dir: /app
    volumes:
      - ./frontend:/app  # bind mounts
      - node_modules:/app/node_modules # volume nommé
    ports:
      - "4200:4200"
    networks:
      - mynetwork

volumes:
  pg_data:
  pgadmin_data:
  node_modules:  # Ajout du volume nommé node_modules
  vendor:  # Ajout du volume nommé vendor
  var:  # Ajout du volume nommé var


networks:
  mynetwork: