

services:

  apache:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
    networks:
      - mynetwork


  php:
    build:
      context: ./backend  # chemin du Dockerfile
    container_name: php-symfony
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/vendor:/var/www/html/vendor
      - ./backend/var:/var/www/html/var
      - ./backend/composer.json:/var/www/html/composer.json
      - ./backend/composer.lock:/var/www/html/composer.lock
    networks:
      - mynetwork
    depends_on:
      - postgres
    # command: ["apache2-foreground"]  # plus besoin car géré par le Dockerfile/docker_entrypoint.sh




  postgres:
    image: postgres:15  # Utilisez une version spécifique de PostgreSQL (plutot que "latest")
    environment:
      POSTGRES_DB: bubblebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork


  pgadmin:
    image: dpage/pgadmin4
    privileged: true
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork
    volumes:
      # - ./pgadmin-data:/var/lib/pgadmin  # Persiste les données de session et la configuration
      - ./pgadmin4/data:/var/lib/pgadmin:rw



  angular:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      # - node_modules:/app/node_modules  # Volume nommé pour node_modules
    # command: ["npm", "start"]
    # command: ["/bin/sh", "-c", "npm install && npm install -g @angular/cli && ng serve --host 0.0.0.0"]
    command: ["/bin/sh", "-c", "npm install && npm install -g @angular/cli && ng serve --host 0.0.0.0 --poll 2000"]
    ports:
      - "4200:4200"
    networks:
      - mynetwork

volumes:
  pg_data:
  node_modules:  # Ajout du volume nommé node_modules


networks:
  mynetwork: