monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.project_dir%/var/log/dev.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
