name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Vérifie le code du dépôt dans l'environnement de build

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm install  

      - name: Run Linter
        run: npm run lint  

      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless  # Exécute les tests unitaires avec Karma en mode tête sans navigateur visible

      - name: Build the application
        run: npm run build -- --configuration production  # Compile l'application Angular en mode production

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: dist/  # Archive les fichiers de production de l'application pour consultation ultérieure

