name: Symfony-CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:

    runs-on: ubuntu-latest  

    services:
      postgres:
        image: postgres:15  
        env:
          POSTGRES_DB: bubblebook  # TODO
          POSTGRES_USER: postgres  # TODO
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2  
          extensions: mbstring, pdo, pdo_pgsql, intl, xml, zip  # Extensions 
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Create .env file for CI
        run: cp .env.test .env  # Copier .env.test en .env
        working-directory: ./backend

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        working-directory: ./backend

      - name: Ensure Doctrine ORM is installed
        run: composer require symfony/orm-pack --no-progress
        working-directory: ./backend

      - name: Run PHPStan
        run: composer phpstan # Analyse du dossier src avec PHPStan 
        working-directory: ./backend

      - name: Run PHP CodeSniffer
        run: composer lint  # Analyse du dossier src avec la norme PSR12 (PHP CodeSniffer)
        working-directory: ./backend

      - name: Prepare database
        env:
          DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/bubblebook"  # TODO (anciennement "pgsql://" et @127.0.0.1 )
        run: |
          php bin/console doctrine:database:create --if-not-exists
          php bin/console doctrine:schema:update --force
          php bin/console doctrine:fixtures:load --no-interaction
        working-directory: ./backend

      - name: Run tests
        env:
          DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/bubblebook"  # TODO (anciennement "pgsql://" et @127.0.0.1 )
        run: php bin/phpunit
        working-directory: ./backend
